<!DOCTYPE html>
<html><head><title>Throws</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">7 references to Throws</div><div class="rA">Assembly-CSharp (7)</div><div class="rG" id="Assembly-CSharp"><div class="rF"><div class="rN">Assets\UnitTests\UnitTests.cs (7)</div>
<a href="../Assets/UnitTests/UnitTests.cs.html#337"><b>337</b>AssertEx.<i>Throws</i>&lt;InvalidOperationException&gt;(() =&gt; Observable.Empty&lt;int&gt;().Aggregate((x, y) =&gt; x + y).Wait());</a>
<a href="../Assets/UnitTests/UnitTests.cs.html#6097"><b>6097</b>AssertEx.<i>Throws</i>&lt;ArgumentOutOfRangeException&gt;(() =&gt; range.Skip(-1));</a>
<a href="../Assets/UnitTests/UnitTests.cs.html#7727"><b>7727</b>AssertEx.<i>Throws</i>&lt;ArgumentOutOfRangeException&gt;(() =&gt; Observable.Range(1, -1).ToArray().Wait());</a>
<a href="../Assets/UnitTests/UnitTests.cs.html#9411"><b>9411</b>AssertEx.<i>Throws</i>&lt;ObjectDisposedException&gt;(() =&gt; subject.OnNext(0));</a>
<a href="../Assets/UnitTests/UnitTests.cs.html#9412"><b>9412</b>AssertEx.<i>Throws</i>&lt;ObjectDisposedException&gt;(() =&gt; subject.OnError(new Exception()));</a>
<a href="../Assets/UnitTests/UnitTests.cs.html#9413"><b>9413</b>AssertEx.<i>Throws</i>&lt;ObjectDisposedException&gt;(() =&gt; subject.OnCompleted());</a>
<a href="../Assets/UnitTests/UnitTests.cs.html#9461"><b>9461</b>AssertEx.<i>Throws</i>&lt;ArgumentOutOfRangeException&gt;(() =&gt; range.Take(-1));</a>
</div>
</div>
</body></html>