<!DOCTYPE html>
<html><head><title>Catch</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">3 references to Catch</div><div class="rA">UniRx.Tests (3)</div><div class="rG" id="UniRx.Tests"><div class="rF"><div class="rN">DisposableTest.cs (1)</div>
<a href="../DisposableTest.cs.html#47"><b>47</b>AssertEx.<i>Catch</i>&lt;InvalidOperationException&gt;(() =&gt; d.Disposable = id2);</a>
</div>
<div class="rF"><div class="rN">Observable.GeneratorTest.cs (1)</div>
<a href="../Observable.GeneratorTest.cs.html#20"><b>20</b>AssertEx.<i>Catch</i>&lt;TimeoutException&gt;(() =&gt;</a>
</div>
<div class="rF"><div class="rN">Tools\ChainingAssertion.Unity.cs (1)</div>
<a href="../Tools/ChainingAssertion.Unity.cs.html#168"><b>168</b>var exception = <i>Catch</i>&lt;T&gt;(testCode, message);</a>
</div>
</div>
</body></html>