<!DOCTYPE html>
<html><head><title>Throw</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">17 references to Throw</div><div class="rA">UniRx (2)</div><div class="rG" id="UniRx"><div class="rF"><div class="rN">Observable.ErrorHandling.cs (1)</div>
<a href="../Observable.ErrorHandling.cs.html#126"><b>126</b>: Observable.<i>Throw</i>&lt;TSource&gt;(ex);</a>
</div>
<div class="rF"><div class="rN">Operators\Defer.cs (1)</div>
<a href="../Operators/Defer.cs.html#26"><b>26</b>source = Observable.<i>Throw</i>&lt;T&gt;(ex);</a>
</div>
</div>
<div class="rA">UniRx.Tests (15)</div><div class="rG" id="UniRx.Tests"><div class="rF"><div class="rN">DoTest.cs (7)</div>
<a href="../../UniRx.Tests/DoTest.cs.html#44"><b>44</b>Observable.Range(1, 5).Concat(Observable.<i>Throw</i>&lt;int&gt;(new Exception())).Do(x =&gt; list.Add(x), ex =&gt; list.Add(100), () =&gt; list.Add(1000)).Subscribe(_ =&gt; { }, _ =&gt; { }, () =&gt; { });</a>
<a href="../../UniRx.Tests/DoTest.cs.html#60"><b>60</b>Observable.Range(1, 5).Concat(Observable.<i>Throw</i>&lt;int&gt;(new Exception())).Do(observer).Subscribe(_ =&gt; { }, _ =&gt; { }, () =&gt; { });</a>
<a href="../../UniRx.Tests/DoTest.cs.html#76"><b>76</b>Observable.Range(1, 5).Concat(Observable.<i>Throw</i>&lt;int&gt;(new Exception())).DoOnError(_ =&gt; list.Add(100)).Subscribe(_ =&gt; { }, _ =&gt; { }, () =&gt; { });</a>
<a href="../../UniRx.Tests/DoTest.cs.html#92"><b>92</b>Observable.Range(1, 5).Concat(Observable.<i>Throw</i>&lt;int&gt;(new Exception())).DoOnCompleted(() =&gt; list.Add(1000)).Subscribe(_ =&gt; { }, _ =&gt; { }, () =&gt; { });</a>
<a href="../../UniRx.Tests/DoTest.cs.html#108"><b>108</b>Observable.Range(1, 5).Concat(Observable.<i>Throw</i>&lt;int&gt;(new Exception())).DoOnTerminate(() =&gt; list.Add(1000)).Subscribe(_ =&gt; { }, _ =&gt; { }, () =&gt; { });</a>
<a href="../../UniRx.Tests/DoTest.cs.html#128"><b>128</b>Observable.Range(1, 5).Concat(Observable.<i>Throw</i>&lt;int&gt;(new Exception()))</a>
<a href="../../UniRx.Tests/DoTest.cs.html#147"><b>147</b>Observable.<i>Throw</i>&lt;int&gt;(new Exception())</a>
</div>
<div class="rF"><div class="rN">Observable.ErrorHandlingTest.cs (5)</div>
<a href="../../UniRx.Tests/Observable.ErrorHandlingTest.cs.html#35"><b>35</b>var xs = Observable.Return(2, Scheduler.ThreadPool).Concat(Observable.<i>Throw</i>&lt;int&gt;(new InvalidOperationException()))</a>
<a href="../../UniRx.Tests/Observable.ErrorHandlingTest.cs.html#51"><b>51</b>Observable.Return(2).Concat(Observable.<i>Throw</i>&lt;int&gt;(new Exception())),</a>
<a href="../../UniRx.Tests/Observable.ErrorHandlingTest.cs.html#52"><b>52</b>Observable.Return(99).Concat(Observable.<i>Throw</i>&lt;int&gt;(new Exception())),</a>
<a href="../../UniRx.Tests/Observable.ErrorHandlingTest.cs.html#68"><b>68</b>Observable.Return(2).Concat(Observable.<i>Throw</i>&lt;int&gt;(new Exception())),</a>
<a href="../../UniRx.Tests/Observable.ErrorHandlingTest.cs.html#69"><b>69</b>Observable.Return(99).Concat(Observable.<i>Throw</i>&lt;int&gt;(new Exception()))</a>
</div>
<div class="rF"><div class="rN">Observable.GeneratorTest.cs (1)</div>
<a href="../../UniRx.Tests/Observable.GeneratorTest.cs.html#104"><b>104</b>Observable.<i>Throw</i>&lt;string&gt;(ex).Materialize().ToArray().Wait().IsCollection(Notification.CreateOnError&lt;string&gt;(ex));</a>
</div>
<div class="rF"><div class="rN">ObservableTest.cs (2)</div>
<a href="../../UniRx.Tests/ObservableTest.cs.html#287"><b>287</b>m = Observable.Range(1, 3).Concat(Observable.<i>Throw</i>&lt;int&gt;(new Exception())).Materialize().ToArrayWait();</a>
<a href="../../UniRx.Tests/ObservableTest.cs.html#304"><b>304</b>Observable.Range(1, 3).Concat(Observable.<i>Throw</i>&lt;int&gt;(new Exception())).Materialize()</a>
</div>
</div>
</body></html>